### ISSUE TITLE
output shape doesn't match

### ISSUE THREAD

**Issue by alexschultz** [zombie0117/yolov3-tiny-onnx-TensorRT#2]
<type 'tuple'>: (<type 'exceptions.ValueError'>, 'cannot reshape array of size 8112 into shape (1,18,13,13)', <traceback object at 0x7f7de8117950>)

Any idea why my output shape doesn't match the expected shape?
![output-shape](https://user-images.githubusercontent.com/1521763/64385962-de082380-d005-11e9-8af8-f9020d5c1785.png)

**Comment by SurionAndrew** [comment]
I Have the same problem:
it outputs "time spent: 0.0322258472443" so it succeeded

yolov3-tiny.weights = 35.4 MB
yolov3-tiny.onnx = 35.4 MB
yolov3-tiny.trt = 48.2 MB

Jetson Nano: Jetpack 4.2.1
python      2.7
onnx        1.4.1 
pycuda    2019.1.2
tensorrt    5.1.6.1

**Comment by SurionAndrew** [comment]
overriding the output_shapes on line 171 of onnx_to_tensorrt.py  gave me valid results

#output_shapes = output_shapes_dic[str(input_size)] <-------  original
output_shapes = [(batch_size, 255, 13, 13), (batch_size, 255, 26, 26)] <-------  Work Around
