### ISSUE TITLE
File "onnx_to_tensorrt.py", line 143, in <listcomp>     [cuda.memcpy_htod_async(inp.device, inp.host, stream) for inp in inputs]

### ISSUE THREAD

**Issue by xcaizewu** [zombie0117/yolov3-tiny-onnx-TensorRT#8]
![1573646595(1)](https://user-images.githubusercontent.com/48117810/68762404-13a63a00-0651-11ea-957d-0feef9f78992.png)

when i run 'python onnx_to_tensorrt.py', get this error

Who can help me

**Comment by kunyao2015** [comment]
@xcaizewu I met the same error ,how to solve this error?

**Comment by xcaizewu** [comment]
@kunyao2015 中国人吧 你测试的这个trt是不是另一台设备生成的？如果是删除这个trt，重新在当前设备生成新的trt文件

**Comment by kunyao2015** [comment]
就是当前设备生成的trt，还是出现问题

**Comment by xcaizewu** [comment]
@kunyao2015 时间太长记不太清是怎么解决的了 要不我把我这个版本给你发一份 你把代码替换一下试试

**Comment by kunyao2015** [comment]
@xcaizewu 感谢老哥，我试成功了，原因是我的输入分辨率和配置文件中的分辨率写的不一样导致的，改了就好了

**Comment by xcaizewu** [comment]
@kunyao2015 好的
